{   'active': False,
    'application': False,
    'author': 'Marc Wimmer',
    'category': 'tools',
    'css': [],
    'demo_xml': [],
    'depends': ['base', 'sale', 'excel_module'],
    'description': '',
    'installable': True,
    'js': [],
    'name': 'excel test',
    'qweb': [],
    'test': [],
    'update_xml': ['reports.xml'],
    'version': '11.0.1.0',
    'web': False}
