{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': [],
    'data': ['views/stock_location_form.xml'],
    'demo_xml': [],
    'depends': ['stock'],
    'installable': True,
    'js': [],
    'name': 'stock_quickinventur_on_need',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0'}
