{   'active': False,
    'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'category': 'uncategorized',
    'css': [],
    'data': [   'views/menu.xml',
                'views/search_recordrules.xml',
                'views/search_views.xml'],
    'demo_xml': [],
    'depends': ['base'],
    'description': 'Link to often used things for admins (scheduler, menuitems, actions...)',
    'installable': True,
    'js': [],
    'name': 'fav_shortcuts',
    'qweb': [],
    'test': [],
    'update_xml': [   'views/menu.xml',
                      'views/search_recordrules.xml',
                      'views/search_views.xml'],
    'version': '1.0',
    'web': False}
