{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': [],
    'data': ['views/assets.xml'],
    'demo_xml': [],
    'depends': ['base', 'web'],
    'installable': True,
    'js': ['static/messagebox.js'],
    'name': 'raise_message_box',
    'qweb': [],
    'test': [],
    'version': '13.0.1.0'}
