#!/bin/bash
set +x
ARGS=( "$@" )

function startup() {
	set -e
	DIR=$( cd "$( /usr/bin/dirname "${BASH_SOURCE[0]}" )" && pwd )
	export DIR="$DIR"

	eval "export $(grep PROJECT_NAME "$DIR/settings")"

	# create empty file, so that simple bash runs
	settings_override_file="$DIR/settings.override"
	if [[ ! -f "$settings_override_file" ]]; then
		touch "$settings_override_file"
	fi
	export HOSTNAME_TO_USE="$HOST"
}

function show_help() {
	if [[ "$1" == '--help' ]]; then
		echo "If you experience problems, try to call"
		echo ""
		echo "$DIR/odoo --fix"
		echo ""
		echo "- docker-container admin bash is updated by that"
		exit 0
	fi
}

function fix() {
	if [[ "$1" == '--fix' ]]; then
		cd "$DIR/config/simplebash"
		./rebuild.sh

		cd "$DIR/config/telegrambot"
		/usr/local/bin/docker-compose build
		exit 0
	fi
}

function remove_old_bash() {
	cd "$DIR/config/simplebash" || exit -1
	/usr/local/bin/docker-compose rm -f simplebash 1>/dev/null 2>&1
}


function collect_extra_volumes() {
	extra_volumes=()

	if [[ -n "$2" ]]; then
		if [[ "$1" == "backup" || "$1" == "backup-db" || "$2" == "backup-files" ]]; then
			extra_volumes=("-v $2:$2")
		elif [[ "$1" == "restore" || "$1" == "restore-files" || "$2" == "restore-db" ]]; then
			if [[ -f "$2" ]]; then
				dir=$(dirname "$2")
				extra_volumes+=("-v $dir:$dir")
			fi
			if [[ -f "$3" ]]; then
				dir=$(dirname "$3")
				extra_volumes+=("-v $dir:$dir")
			fi
		fi
	fi
}

function build_command() {
	# using absolute path, to work in crontab
	if [[ -n "$DISPLAY" ]]; then
		xhost +local:"$HOSTNAME_TO_USE"  >/dev/null
	fi
	docker_group_id="$(cut -d : -f3 <(getent group docker))"
	command=(/usr/local/bin/docker-compose)
	command+=(run)
	command+=(--service-ports)
	command+=(--name "odoo_bash_$(/usr/bin/uuidgen)")
	command+=(-e HOST_ODOO_HOME="$DIR")
	command+=(-e ODOO_HOME="$DIR")
	command+=(-e UID="$UID")
	command+=(-e USER="$USER")
	command+=(-e DOCKER_GROUP_ID="$docker_group_id")
	if [[ -n "${extra_volumes[*]}" ]]; then
		command+=( "${extra_volumes[@]}" )
	fi
	command+=(simplebash)
	command+=("$DIR/admin/odoo-admin")
	command+=( "${ARGS[@]}" )
}

function run_command() {
	eval "${command[@]@Q}"
}

startup
show_help "${ARGS[@]}"
fix "${ARGS[@]}"
remove_old_bash
collect_extra_volumes "${ARGS[@]}"
build_command
run_command
