#!/usr/bin/env python3
from pathlib import Path
import sys
import os
import inspect


SCRIPT_DIRECTORY = Path(inspect.getfile(inspect.currentframe())).absolute().parent

if os.getenv("DOCKER_MACHINE", "") == "1":
    raise Exception("Cannot execute this script in docker container.")
os.environ['HOST_HOME'] = os.environ['HOME']
os.environ['ODOO_HOME'] = str(SCRIPT_DIRECTORY)

sys.path.append(str(SCRIPT_DIRECTORY / 'tools'))
from odoo_tools import cli # NOQA
from odoo_tools import Commands # NOQA
from odoo_tools import HOST_RUN_DIR # NOQA
from odoo_tools.myconfigparser import MyConfigParser # NOQA

os.environ['RUN_DIR'] = str(HOST_RUN_DIR)

if __name__ == '__main__':
    if not HOST_RUN_DIR:
        import click
        click.echo("Please enter into an odoo directory, which contains a MANIFEST file.")
        sys.exit(1)
    if not HOST_RUN_DIR.exists():
        with cli.make_context('odoo', ['-f']) as ctx:
            Commands.invoke(ctx, 'reload')
    cli()
