{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': [],
    'data': ['cronjobs.xml'],
    'demo': [],
    'demo_xml': [],
    'depends': ['queue_job'],
    'installable': True,
    'name': 'queue_jobs_requeue_terminated',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0'}
