{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': True,
    'category': 'Odoo Docker Environment',
    'css': [],
    'data': [   'views/branch_tree.xml',
                'views/container_form.xml',
                'views/container_tree.xml',
                'views/instance_form.xml',
                'views/instance_tree.xml',
                'views/menu.xml',
                'views/new_branch.xml',
                'views/version_commander_form.xml'],
    'demo_xml': [],
    'depends': ['base'],
    'description': '',
    'installable': True,
    'js': [],
    'name': 'container_admin',
    'qweb': [],
    'test': [],
    'version': '1.0',
    'web': False}
