{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': True,
    'category': 'Odoo Docker Environment',
    'css': [],
    'data': ['views/container_tree.xml', 'views/menu.xml'],
    'demo_xml': [],
    'depends': ['base'],
    'description': '',
    'installable': True,
    'js': [],
    'name': 'container_admin',
    'qweb': [],
    'test': [],
    'version': '1.0',
    'web': False}
