#!/usr/bin/env python
import shutil
import os
import sys
dest = os.path.join(os.getcwd(), sys.argv[1])

CUSTOMS = os.getenv("CUSTOMS")
VERSION = os.getenv("ODOO_VERSION")

if not CUSTOMS or not VERSION:
    raise Exception("Customs and version required")

ODOO_HOME = os.getenv("ODOO_HOME")
if not ODOO_HOME:
    raise Exception("ODOO_HOME missing")

shutil.copytree(os.path.join(ODOO_HOME, 'admin/module_template', VERSION), dest)
for root, dirs, files in os.walk(dest):
    if '.git' in dirs:
        dirs.remove('.git')
    for filepath in files:
        filepath = os.path.join(root, filepath)
        with open(filepath, 'r') as f:
            content = f.read()
        content = content.replace("__module_name__", sys.argv[1])
        with open(filepath, 'w') as f:
            f.write(content)
