#!/bin/bash
set -e
set -x

if [[ -z "$2" ]]; then
	echo "Please provide name and version."
	exit -1
fi
VERSION=$2
CUSTOMS=$1

cd $ODOO_HOME/customs
[[ -d "$CUSTOMS" ]] && {
	echo "Customs $CUSTOMS already exists."
	exit -1
}

cd $ODOO_HOME/customs
mkdir -p $CUSTOMS
rsync $ODOO_HOME/admin/customs_template/$VERSION/ $CUSTOMS/ -ar
cd $CUSTOMS
git init .
