#!/usr/bin/python
"""
Manages versioning of submodules.

"""
import sys
import subprocess
import module_tools
import odoo_config
import shutil
import os
import tempfile
from git import Repo
from git import Actor
from myconfigparser import MyConfigParser
import inspect
current_file = os.path.abspath(inspect.getfile(inspect.currentframe())) # script directory

if len(sys.argv) >= 2:
    action = sys.argv[1]
else:
    action = None

customs_dir = odoo_config.customs_dir()

def display_help():
    print "How to use:"
    print ""
    print "odoo-git new-ticket <ticketname>"
    print
    print "odoo-git master :current ticket is used"
    print ""
    print "odoo-git deploy <ticketname>"
    print ""
    print ""
    sys.exit(-1)

def action_new_ticket():
    if action in ['new-ticket', 'deploy'] and len(sys.argv) < 3:
        print "Please provide ticket name!"
        sys.exit(-1)
    branch = sys.argv[2]
    raise Exception("check if dirty")
    try:
        subprocess.check_call(['/usr/bin/git', 'stash'], cwd=customs_dir).strip()
    except: pass
    subprocess.check_call(['/usr/bin/git', 'checkout', '-f', 'deploy'], cwd=customs_dir)
    subprocess.check_call(['/usr/bin/git', 'checkout', '-b', branch], cwd=customs_dir)
    print ""
    print ""
    print "Switch to new branch: {}".format(branch)
    print ""
    print ""

def unit_tests_git():
    r = {
    }

    def reset_repo():
        global repo

        path = tempfile.mkdtemp(suffix='')

        path_repo = os.path.join(path, 'repo1')
        print path_repo
        os.mkdir(path_repo)

        repo = Repo.init(path_repo, bare=False)
        print repo.is_dirty()
        file1 = os.path.join(path_repo, 'file1.txt')
        with open(file1, 'w') as f:
            f.write("1")
        r['repo'] = repo
        r['file1'] = file1
        r['author'] = Actor("User1", "user1@home.de")

        r['path_subrepo'] = os.path.join(path, 'subrepo')
        r['subrepo'] = Repo.init(r['path_subrepo'])
        file1 = os.path.join(r['path_subrepo'], 'subfile1.txt')
        with open(file1, 'w') as f:
            f.write("sub 1")

    def case1():
        "commit a file"
        global repo
        reset_repo()
        repo = r['repo']
        file1 = r['file1']
        assert len(repo.untracked_files) == 1
        changed_files = [item.a_path for item in repo.index.diff(None)]
        #staged_files = [item.a_path for item in repo.index.diff("HEAD")]
        repo.index.add([os.path.basename(file1)])
        repo.index.commit("msg1", author=r['author'], committer=r['author'])
        #repo.git.add(update=True) # no new files

        with open(file1, 'w') as f:
            f.write("2")
        changed_files = [item.a_path for item in repo.index.diff(None)]
        repo.index.add(changed_files)
        repo.index.commit("msg2", author=r['author'], committer=r['author'])

        file2 = os.path.join(repo.working_dir, 'file2.txt')
        with open(file2, 'w') as f:
            f.write("3")
        assert len(repo.untracked_files) == 1
        repo.index.add(repo.untracked_files)
        repo.index.commit("msg3", author=r['author'], committer=r['author'])

        os.unlink(file2)

        # caution: commit updates and deletes by directory
        # TODO extract following code
        for diff in repo.index.diff(None):
            if not diff.b_mode and not diff.b_blob:
                # deleted
                repo.index.remove(items=[diff.a_path])
            else:
                repo.index.add(items=[diff.a_path])
        repo.index.commit("deleted", author=r['author'], committer=r['author'])

    def case_empty_commit():
        global repo
        reset_repo()
        repo = r['repo']
        file1 = r['file1']
        repo.index.add([os.path.basename(file1)])
        repo.index.commit("msg1", author=r['author'], committer=r['author'])

        # now empty commit
        repo.index.commit("msg empty")

    def case_submodule():
        global repo
        reset_repo()
        repo = r['repo']
        file1 = r['file1']
        assert len(repo.untracked_files) == 1
        changed_files = [item.a_path for item in repo.index.diff(None)]
        #staged_files = [item.a_path for item in repo.index.diff("HEAD")]
        repo.index.add([os.path.basename(file1)])
        repo.index.commit("msg1", author=r['author'], committer=r['author'])

        #clone submodule
        from pudb import set_trace
        set_trace()
        subrepo_dir = 'subrepo'
        repo.clone_from(r['path_subrepo'], os.path.join(repo.working_dir, subrepo_dir))

        repo.index.commit("subrepo added")
        from pudb import set_trace
        set_trace()


    #case1()
    #case_empty_commit()
    case_submodule()

    from pudb import set_trace
    set_trace()


def unit_tests():
    # make new customs
    customs = 'vunittest'

    customs_dir = os.path.join(odoo_config.customs_root(), customs)
    assert '/' + customs in customs_dir, customs_dir

    def make_module(parent_path, modulename):
        os.chdir(parent_path)
        for v in ['7.0', '9.0']:
            subprocess.check_call('mkdir -p "{modulename}/{v}"'.format(**locals()), cwd=parent_path, shell=True)
            with open('{modulename}/{v}/__openerp__.py'.format(**locals()), 'w') as f:
                f.write("{'version': '1.0'}")

    def make_demo_customs(path):
        if os.path.exists(customs_dir):
            shutil.rmtree(customs_dir)
        os.makedirs(customs_dir)
        os.chdir(customs_dir)
        os.system("git init .")
        os.system('mkdir -p common')
        os.system('mkdir -p modules')

        with open(os.path.join(customs_dir, '.version'), 'w') as f:
            f.write("9.0")
        with open(os.path.join(customs_dir, '.odoo.ast'), 'w') as f:
            f.write("")

        # make submodule
        path_modules1 = tempfile.mkdtemp()
        os.chdir(path_modules1)
        make_module(path_modules1, 'submodule1_1')
        make_module(path_modules1, 'submodule1_2')
        make_module(path_modules1, 'submodule1_3')
        make_module(os.path.join(customs_dir, 'modules'), 'module1')
        subprocess.check_call("git init .", cwd=path_modules1, shell=True)
        subprocess.check_call("git add .; git commit -am .", cwd=path_modules1, shell=True)

        # clone submodules into common
        os.chdir(customs_dir)
        subprocess.check_call('git clone "{}" common/submodule1'.format(path_modules1), cwd=customs_dir, shell=True)

    def v(*params):
        cmd = [current_file] + list(params)
        subprocess.check_call(cmd, cwd=customs_dir)

    make_demo_customs(customs_dir)
    odoo_config.set_customs(customs)
    # make demo customs

    print 'Start working on a new ticket - customers ticket number is ticket#1'
    v('new-ticket', 'ticket#1')
    v('new-ticket', 'ticket#2')


actions = {
    'new-ticket': action_new_ticket,
    'unit-test': unit_tests,
    'unit-tests': unit_tests,
    'unit-tests-git': unit_tests_git,
    'help': display_help,
}


if action not in actions:
    print "Invalid verb: {}".format(action)
    display_help()
    sys.exit(-1)
else:
    actions[action]()
