{   'active': True,
    'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': True,
    'conflicts': [],
    'css': [],
    'data': [],
    'demo_xml': [],
    'depends': ['base'],
    'installable': True,
    'js': [],
    'name': 'field_onchange',
    'post_load': 'post_load',
    'qweb': [],
    'sequence': -1,
    'test': [],
    'version': '13.0.1.0'}
