{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'css': [],
    'data': [   'data/cronjobs.xml',
                'views/queue_job_form.xml',
                'views/queue_job_search.xml',
                'views/queue_job_tree.xml',
                'views/severity_rule_tree.xml',
                'views/menu.xml',
                'security/ir.model.access.csv'],
    'demo': [],
    'depends': ['queue_job'],
    'external_dependencies': {'bin': [], 'python': []},
    'name': 'queuejob_error_categories',
    'qweb': [],
    'test': [],
    'version': '13.0.1.0'}
