{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'category': 'uncategorized',
    'css': [],
    'data': [   'views/assets.xml',
                'views/followup_dashboard.xml',
                'views/menu.xml'],
    'demo_xml': [],
    'depends': ['base', 'followup', 'web'],
    'description': '',
    'installable': True,
    'js': ['static/src/js/followup_dashboard.js'],
    'name': 'followup_dashboard',
    'qweb': ['static/src/xml/followup_dashboard.xml'],
    'test': [],
    'version': '1.0',
    'web': True}
