{   'active': False,
    'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': True,
    'css': [],
    'data': ['models/basicchecks.xml'],
    'demo': [],
    'demo_xml': [],
    'depends': ['base', 'datapolice', 'stock'],
    'description': '',
    'installable': True,
    'js': [],
    'name': 'datapolice_checks_stock',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0',
    'web': False}
