{   'active': False,
    'application': False,
    'author': 'Marc Wimmer',
    'category': 'tools',
    'css': [],
    'data': ['data/lang.xml', 'view_lang_form.xml'],
    'demo_xml': [],
    'depends': ['base'],
    'installable': True,
    'js': [],
    'name': 'excel_module',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0',
    'web': False}
