{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': ['report/styles.less'],
    'data': ['views/assets.xml', 'views/report_form.xml'],
    'demo_xml': [],
    'depends': ['base'],
    'installable': True,
    'js': [],
    'name': 'report_pdf_watermark',
    'qweb': [],
    'test': [],
    'version': '13.0.1.0'}
