{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': [],
    'data': [   'security/groups.xml',
                'data/config.xml',
                'views/log_requests.xml',
                'views/menu.xml',
                'security/ir.model.access.csv'],
    'demo_xml': [],
    'depends': ['base'],
    'installable': True,
    'js': [],
    'name': 'request_detail_log',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0'}
