{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': [],
    'data': [   'data/cronjobs.xml',
                'views/queue_job_function_form.xml',
                'views/queue_job_function_tree.xml'],
    'demo': [],
    'demo_xml': [],
    'depends': ['queue_job'],
    'installable': True,
    'name': 'cronjob_requeue_queuejobs',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0'}
