#!/bin/bash
# holt neues branch version und merged in aktuellen branch

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )

echo # bringing detached heads to master and current changes
tempbranch=temp121212
# falls man aenderungen auf detached head gemacht hat werden diese auf den master damit geholt
git submodule foreach "git add ."
git submodule foreach "git commit -am 'autocommit durch git-sub-update' || echo '' "
git submodule foreach git checkout -b $tempbranch
git submodule foreach git branch -f master $tempbranch
git submodule foreach git checkout master
git submodule foreach git branch -D $tempbranch

$DIR/git-sub-set-branch
git submodule update --init --remote --merge
git add .
git commit -am sub
git push
$DIR/git-sub-push-unpushed
