#!/bin/bash
set -e

cd "$ODOO_HOME/data/src/customs/$CUSTOMS" || exit -1

if [[ ! -d common ]]; then
    echo "Please go to customs root (missing common-directory)"
    exit -1
fi

if [[ -z "$ODOO_VERSION" ]]; then
	echo "Version required"
	exit -1
fi

echo "Adding OCA module $1 as subtree"
git subtree -q add --prefix="OCA/$1" --squash "https://github.com/OCA/$1.git" "$ODOO_VERSION"
cd "OCA/$1" || exit -1
cd ../.. || exit -1

chown "$DEFAULT_USER":"$DEFAULT_USER" "OCA/$1"

echo ""
echo "Added OCA Module $1 as subtree"
echo ""

