#!/bin/bash
set -x
set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [[ ! -d common ]]; then
    echo "Please go to customs root (missing common-directory)"
    exit -1
fi

if [[ ! -d .git ]]; then
    echo "Must have .git directory to avoid clone in parent directory"
    exit -1
fi

if [[ -z "$VERSION" ]]; then
	echo "Version required"
	exit -1
fi

echo "Adding OCA module $1 as subtree"
git subtree -q add --prefix="OCA/$1" --squash "https://github.com/OCA/$1.git" "$VERSION"
cd "OCA/$1" || exit -1
cd ../.. || exit -1

echo ""
echo "Added OCA Module $1 as subtree"
echo ""
