#!/usr/bin/env python3
import glob
import click
import fileinput
from datetime import datetime
import hashlib
import pickle
import base64
import copy
import inquirer
import pipes
import types
import sys
import re
import signal
import os
import logging
import importlib
import time
import inspect
import yaml
import shutil
import tempfile
import docker
import shlex
import traceback
import json
from tabulate import tabulate
from inspect import getmembers, isfunction
from retrying import retry
from threading import Thread
from logging import FileHandler
from module_tools.myconfigparser import MyConfigParser
from module_tools import odoo_config
from adminlib import tools, files, dirs, commands, cli
from adminlib.tools import _file2env
from adminlib.tools import _remove_temp_directories

try:
    from pudb import set_trace
except Exception:
    set_trace = None

def trace():
    if os.getenv("DEVMODE", "") == "1":
        if set_trace:
            set_trace()

def _cleanup():
    _remove_temp_directories()


if __name__ == '__main__':
    args = sys.argv[1:]
    if args:
        if args[0] == 'tool':
            sys.exit(0)

    try:
        cli()
    finally:
        _cleanup()
