#!/bin/bash
# setzt alle submodule auf den branch aus .gitmodules
# und macht ein fast forward auf HEAD
git submodule foreach -q --recursive '

if [ "$name" != "odoo" ]; then 
	set -e
	git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master) 
	git merge --ff-only origin/$(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master)
else
	echo "Not touching odoo repo"
fi
'
