#!/bin/bash
set -e
set -x

if [[ ! -d common ]]; then
    echo "Directory common not found - are you in root?"
    exit 1
fi

if [[ ! -d ".git" ]]; then
	git init .
fi

for i in ${1//,/ };
do
	git subtree add --prefix="common/$i" --squash git.mt-software.de:"/git/openerp/modules/$i" master
done

