#!/bin/bash
set -e
set -x

if [[ ! -d common ]]; then
    echo "Directory common not found - are you in root?"
    exit 1
fi

if [[ ! -d ".git" ]]; then
	git init .
fi

for i in $(echo $1 | sed "s/,/ /g");
do
	git submodule add -b master --force git.mt-software.de:/git/openerp/modules/$i common/$i
done

