{   'active': False,
    'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'category': 'uncategorized',
    'css': [],
    'data': [   
        'views/views.xml',
                ],
    'demo_xml': [],
    'depends': ['base'],
    'description': '',
    'installable': True,
    'js': [],
    'name': 'debugging',
    'qweb': [],
    'test': [],
    'version': '13.0.1.0',
    'web': False}
