{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de), Michael Tietz '
              'mtietz@mt-software.de',
 "auto_install": True,
    'css': [],
    'data': [   'data/cronjobs.xml',
                'views/queue_job_form.xml',
                'views/queue_job_tree.xml'],
    'demo': [],
    'depends': ['queue_job'],
    'external_dependencies': {'bin': [], 'python': []},
    'name': 'queuejob_extras',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0'}
