{   'active': False,
    'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': True,
    'category': 'uncategorized',
    'css': [],
    'data': ['models/basicchecks.xml'],
    'demo_xml': [],
    'depends': ['base', 'datapolice', 'product', 'purchase'],
    'description': '',
    'installable': True,
    'js': [],
    'name': 'datapolice_checks_purchase',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0',
    'web': False}
