FROM ubuntu:14.04
# if in customizations is an asterisk directory, then enable asterisk, otherwise not
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y linux-headers-generic
RUN apt-get install -y subversion git

WORKDIR /root
RUN mkdir -p .ssh

WORKDIR /root/.ssh
ADD id_rsa id_rsa
ADD ssh_config_repo config
RUN chmod 600 id_rsa

ADD ./etc/asterisk /opt/etc.base

ADD menuselect.makeopts /tmp/menuselect.makeopts
ADD build_asterisk.sh /tmp/build_asterisk.sh
RUN chmod a+x /tmp/build_asterisk.sh
RUN /tmp/build_asterisk.sh

#  init jobs
RUN make config 
ADD run.sh /run.sh
RUN chmod a+x /run.sh


CMD ["/run.sh"]
