{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': [],
    'data': ['data/execute.xml'],
    'demo_xml': [],
    'depends': ['base'],
    'installable': True,
    'js': [],
    'name': 'anonymize',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0'}
