{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': True,
    'conflicts': [],
    'external_dependencies': {'bin': [], 'python': ['names']},
    'css': [],
    'data': [],
    'demo_xml': [],
    'depends': ['base'],
    'installable': True,
    'js': [],
    'name': 'anonymize',
    "post_init_hook": "post_init_hook",
    'qweb': [],
    'test': [],
    'version': '13.0.1.0'}
