{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': [],
    'data': [   'views/quant_search.xml',
                'views/quants_tree.xml',
                'views/stock_picking_form.xml',
                'views/menu.xml'],
    'demo': [],
    'demo_xml': [],
    'depends': ['datapolice', 'stock', 'stock_quickinventur_on_need'],
    'installable': True,
    'js': [],
    'name': 'stock_check_fix_quant_reservations',
    'qweb': [],
    'test': [],
    'version': '11.0.1.0'}
